version: '3'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - portfolio-test

  portfolio-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - CI=true
